server:
  port: 8041

spring:
  cloud:
    config:
      server:
        svn:
          uri: svn://106.15.88.27/config
          username: admin
          password:
        default-label: trunk
  profiles:
    active: subversion
  application:
    name: spring-cloud-config-client